name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04 # تحديد إصدار نظام التشغيل لضمان التوافق
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer Action
        uses: GearUp-Dev/buildozer-action@v2
        with:
          python_version: 3.10
          buildozer_version: stable
          # هذا الـ Action سيقوم بالبناء وإخراج الملف في قسم Artifacts
